### PR TITLE
fix: Add Discount Amount field to show payment dialog

### PR DESCRIPTION
**Pull request by Irfan778899**
sajinprgif

### CODE REVIEW

**Comment by akashkrishna619** [comment]
@Irfan778899 since consultation charge is made editable it is better to have a validation with the amount. Can you do that?

**Comment by mujeerhashmi** [comment]
@akashkrishna619 You mean to validate if consultation charge is not zero ?
Also we have had use cases where some appointments need to be done free of cost. Can we manage that with 100% discount with is free check ?

**Comment by Irfan778899** [comment]
> @Irfan778899 since consultation charge is made editable it is better to have a validation with the amount. Can you do that?

@akashkrishna619 Added a validation that, If consultation charge is 0, the invoice will be created with 100 % discount and the consultation would be a free consultation.

**Comment by kalungia** [comment]
If consultation charge is 0, no invoice should be created.

**Comment by Irfan778899** [comment]
Have updated the PR by adding a discount field in payment dialog popup and reverted the consultation charge field to read only.

**Comment by Sajinsr** [comment]
@Irfan778899 Discount Amount field in dialog remains editable after creating the invoice, can you make that read only after creating invoice

**Comment by Irfan778899** [comment]
Have updated the PR by making both mode_of_payment and discount_amount fields disabled in dialog after creation of Sales Invoice.

**Comment by akashkrishna619** [comment]
@Irfan778899 can you add screenshots showing this change, also can you update the pr title as well

**Comment by akashkrishna619** [comment]
> @Irfan778899 can you add screenshots showing this change, also can you update the pr title as well

or @Sajinsr  can add if he have test instance with him

**Comment by Irfan778899** [comment]
Have updated the PR title. Also attached a screenshot taken after clicking the create invoice buttion.

Screenshot for Discount field added

**Comment by Irfan778899** [comment]
Adding additional screenshots

Screenshot of "Additional Discount" section of Invoice document where the discount is added to  "Additional Discount Amount" field.
Screenshot of Additional discount section

Screenshot of "Payments" tab of Invoice document where the amount paid after discount is showing.
Screenshot of payment tab of Invoice document

Screenshot of "Paid Amount" field of Patient Appointment
Screenshot of Paid Amount field of Patient Appointment

Screenshot of "Items" Section of Patient Appointment
Screenshot of Items section of Patient Appointment

**Review by akashkrishna619 — APPROVED** [review]

**Pull request merged**
