### PR TITLE
fix(sales invoice): get healthcare items from clinical procedure

### PR DESCRIPTION
**Pull request by tamburro92**
If you create a **Clinical Procedure** billable ad use a custom Item Code, instead of procedure name same, fetch the healthcare item from **Invoice Sales** will fail because it won't find the right item code.
To fix you have to retrieve, together the procedure name, the right item code.

Screenshot 2024-02-18 alle 20 51 28

### CODE REVIEW

**Comment by tamburro92** [comment]
ok now I have read the rule about "commitlint"...
let me know if I have to apply a new pull request.

**Comment by akashkrishna619** [comment]
> ok now I have read the rule about "commitlint"... let me know if I have to apply a new pull request.

@tamburro92 ithe changes you did in the title  need to be done in the commit messages. Also linters issue need to be solved

**Comment by tamburro92** [comment]
ok I'm done

**Comment by akashkrishna619** [comment]
@tamburro92 please change the target branch to develop

**Comment by akashkrishna619** [comment]
changing target to base branch to develop as this will be appicable to v14 as well

**Comment by akashkrishna619** [comment]
@tamburro92 can you test this with other invoicing as well? (Service Request/ Medication Request / Encounter etc..)

**Comment by akurungadam** [comment]
can't reproduce this, closing for now.. thanks

**Pull request closed without merging**
