### PR TITLE
feat: New Field for calendar View

### PR DESCRIPTION
**Pull request by RehanIqbalIT**
[Add] New Field for calendar View to show Practitioner name, Patient Name and Procedure template on calendar

### CODE REVIEW

**Comment by kalungia** [comment]
I do think the Practitioner name and Patient Name are helpful on the calendar but not the Procedure Template.

**Comment by RehanIqbalIT** [comment]
> I do think the Practitioner name and Patient Name are helpful on the calendar but not the Procedure Template.

It is very helpful to view appointment of the Procedure for the day.

**Comment by kalungia** [comment]
> > I do think the Practitioner name and Patient Name are helpful on the calendar but not the Procedure Template.
> 
> It is very helpful to view appointment of the Procedure for the day.

After a day at the hospital, I see that this is important.

**Comment by akurungadam** [comment]
will add this at a later point, thanks. closing for now, @Sajinsr please note

**Pull request closed without merging**
