### PR TITLE
feat: Add health card feature

### PR DESCRIPTION
**Pull request by mujeerhashmi**
The health card feature allows to define different health card types and the applicable discounts on items/item group for that health card type. The health cards can be created in bulk. The health card can then be assigned to patient, activated and billed.

### CODE REVIEW

**Review by akashkrishna619 — COMMENTED** [review]
It'll be better if you can add screen grabs and description please?

**Comment by mujeerhashmi** [comment]
> It'll be better if you can add screen grabs and description please?

https://user-images.githubusercontent.com/12420747/220035877-633a8e4b-804d-4aee-8fb0-f83a4112c5e8.mp4

**Review by akashkrishna619 — COMMENTED** [review]
Also please add test cases

**Comment by mujeerhashmi** [comment]
Closing this for now. We will send the PR later with test cases.

**Pull request closed without merging**
